# Generated by Django 4.2.4 on 2023-10-05 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('passworld', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Cancelado', 'Cancelado'), ('Aprovado', 'Aprovado')], max_length=200)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantityStock', models.IntegerField()),
                ('code', models.CharField(max_length=200)),
                ('manufacturerName', models.CharField(max_length=200)),
                ('valuePur', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('workStation', models.CharField(choices=[('Posto1', 'Posto1'), ('Posto2', 'Posto2'), ('Posto3', 'Posto3')], max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('passworld', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('year', models.DateField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('valueFinal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoryServicesFk', models.ManyToManyField(related_name='CategoryServices', to='app.categoryservices')),
                ('employee', models.ManyToManyField(related_name='employeeServices', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('availabilityFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.availability')),
                ('employeeFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintanceEmployees', to='app.employee')),
                ('payFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintancePay', to='app.payments')),
                ('productsFk', models.ManyToManyField(related_name='maintanceTools', to='app.products')),
                ('servicesFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
                ('vehiclesFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='app.vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='reserveFk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingAvailability', to='app.reserve'),
        ),
    ]
