# Generated by Django 4.2.4 on 2023-10-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_maintenance_user_maintenance_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='work_station',
            new_name='workStation',
        ),
        migrations.AlterUniqueTogether(
            name='reserve',
            unique_together={('date', 'workStation')},
        ),
    ]
