# Generated by Django 4.2.4 on 2023-10-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_maintenance_productsusedquant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='passworld',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passworld',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='employeeFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenanceEmployees', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='payFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenancePay', to='app.payments'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='productsFk',
            field=models.ManyToManyField(related_name='maintenanceTools', to='app.products'),
        ),
        migrations.AlterField(
            model_name='services',
            name='categoryServicesFk',
            field=models.ManyToManyField(related_name='services', to='app.categoryservices'),
        ),
    ]
