# Generated by Django 4.2.4 on 2023-10-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20231011_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='reserveFk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookingAvailability', to='app.reserve'),
        ),
    ]
