# Generated by Django 4.2.4 on 2023-10-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_availability_reservefk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
