# Generated by Django 4.2.4 on 2023-10-12 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='employeeFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenanceEmployees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='services',
            name='employee',
            field=models.ManyToManyField(related_name='employeeServices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
