# Generated by Django 4.2.4 on 2023-10-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_maintenance_employeefk_alter_services_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
